In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')
import os

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
file_paths = ['/content/drive/MyDrive/data for research/reg2016/Jan2016_eir.xlsx', '/content/drive/MyDrive/data for research/reg2016/feb2016_eir.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_March2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_April2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_May2016.xlsx','/content/drive/MyDrive/data for research/reg2016/eir_June2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_July2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_August2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_September2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_October2016.xlsx', '/content/drive/MyDrive/data for research/reg2016/eir_November2016.xlsx',  '/content/drive/MyDrive/data for research/reg2016/eir_December2016.xlsx'  ]

In [ ]:
# dfs = []

# for file_path in file_paths:
#     if os.path.exists(file_path):
#         df = pd.read_excel(file_path)
#         dfs.append(df)
#     else:
#         print(f"File not found: {file_path}")

In [ ]:
# merged_df = pd.concat(dfs, ignore_index=True)
# merged_df

,CIN,COMPANY NAME,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,...,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 0,Unnamed: 1,Unnamed: 15,Unnamed: 16
0,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U01403AP2016PTC098002,AMEYA INDIA PRIVATE LIMITED,*,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,108000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93747,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,96000,NaN,8228,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93748,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,90000,96000,NaN,8229,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93749,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,NaN,8230,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93750,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8231,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93751,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8232,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

In [ ]:
# common_columns = [
#     'S.No', 'CIN', 'COMPANY NAME', 'DATE OF REGISTRATION', 'MONTH NAME', 'STATE',
#     'ROC', 'CLASS', 'COMPANY STATUS', 'COMPANY TYPE', 'CATEGORY', 'ACTIVITY CODE',
#     'ACTIVITY DESCRIPTION', 'REGISTERED OFFICE ADDRESS'
# ]

# merged_df = pd.DataFrame()

# # Iterate over each Excel file
# for file_path in file_paths:
#     if os.path.exists(file_path):
#         # Read the Excel file skipping the header row
#         df = pd.read_excel(file_path, header=None, dtype=str)  # Ensure all data is read as string

#         # Extract only the common columns
#         extracted_columns = [col for col in common_columns if col in df.iloc[0].values]

#         # Extract the data for the common columns
#         for i, col in enumerate(df.iloc[0]):
#             if col in extracted_columns:
#                 # Remove spaces and replace them with underscores in column names
#                 col_name_cleaned = col.strip().replace(' ', '_')
#                 # If the column is 'DATE OF INCORPORATION', merge it with 'DATE OF REGISTRATION'
#                 if col_name_cleaned == 'DATE_OF_INCORPORATION':
#                     col_data = pd.to_datetime(df.iloc[1:, i], errors='coerce', format='%m/%d/%Y')
#                     # Rename the column to 'DATE OF REGISTRATION' and append to the merged DataFrame
#                     merged_df['DATE OF REGISTRATION'] = col_data.dt.strftime('%m/%d/%Y')
#                 else:
#                     # Extract the column data and append it to the merged DataFrame
#                     merged_df[col_name_cleaned] = df.iloc[1:, i]
#     else:
#         print(f"File not found: {file_path}")

# # Fill missing columns with NaN values
# for col in common_columns:
#     col_name_cleaned = col.strip().replace(' ', '_')
#     if col_name_cleaned not in merged_df.columns:
#         merged_df[col_name_cleaned] = pd.Series(dtype=object)

In [ ]:
# merged_df

,CIN,COMPANY_NAME,STATE,ROC,CATEGORY,CLASS,S.No,DATE_OF_REGISTRATION,MONTH_NAME,COMPANY_STATUS,COMPANY_TYPE,ACTIVITY_CODE,ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS
1,U21098AN2016PTC000279,DIGITAL ARTS TECHNOLOGIES PRIVATE LIMITED,Andaman and Nicobar Islands,RoC-Chennai,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U92419AN2016OPC000280,HIGH SEAS SPORTS CLUB PRIVATE LIMITED (OPC),Andaman and Nicobar Islands,RoC-Chennai,Company limited by shares,OPC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U74900AN2016PTC000281,ROYAL PETROLEUM (ANDAMAN) PRIVATE LIMITED,Andaman and Nicobar Islands,RoC-Chennai,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U45206AN2016PTC000282,AL VIJAY INFRASTRUCTURE PRIVATE LIMITED,Andaman and Nicobar Islands,RoC-Chennai,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,U45400AN2016PTC000283,M.R.L BUILDERS PRIVATE LIMITED,Andaman and Nicobar Islands,RoC-Chennai,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7363,U74900TG2016PTC103483,CLICK2CLINIC HEALTHCARE INDIA PRIVATE LIMITED,Telangana,RoC-Hyderabad,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7364,U74900TG2016PTC103484,TIMES SCIENTIFIC ONLINE PRIVATE LIMITED,Telangana,RoC-Hyderabad,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7365,U74900TG2016PTC103487,COSMO TRADEVISION PRIVATE LIMITED,Telangana,RoC-Hyderabad,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7366,U74900TG2016PTC103501,JCN FINCON SERVICES PRIVATE LIMITED,Telangana,RoC-Hyderabad,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7367,U80211TG2016PTC103502,CHANDU COMMERCE & MANAGEMENT STUDIES PRIVATE L...,Telangana,RoC-Hyderabad,Company limited by shares,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# merged_df.value_counts

<bound method DataFrame.value_counts of                         CIN  \
1     U21098AN2016PTC000279
2     U92419AN2016OPC000280
3     U74900AN2016PTC000281
4     U45206AN2016PTC000282
5     U45400AN2016PTC000283
...                     ...
7363  U74900TG2016PTC103483
7364  U74900TG2016PTC103484
7365  U74900TG2016PTC103487
7366  U74900TG2016PTC103501
7367  U80211TG2016PTC103502

                                           COMPANY_NAME  \
1             DIGITAL ARTS TECHNOLOGIES PRIVATE LIMITED
2           HIGH SEAS SPORTS CLUB PRIVATE LIMITED (OPC)
3             ROYAL PETROLEUM (ANDAMAN) PRIVATE LIMITED
4               AL VIJAY INFRASTRUCTURE PRIVATE LIMITED
5                        M.R.L BUILDERS PRIVATE LIMITED
...                                                 ...
7363      CLICK2CLINIC HEALTHCARE INDIA PRIVATE LIMITED
7364            TIMES SCIENTIFIC ONLINE PRIVATE LIMITED
7365                  COSMO TRADEVISION PRIVATE LIMITED
7366                JCN FINCON SERVICES PRIVATE LIMITED
7367  CHANDU COMMERCE & MANAGEMENT STUDIES PRIVATE L...

                            STATE            ROC                   CATEGORY  \
1     Andaman and Nicobar Islands    RoC-Chennai  Company limited by shares
2     Andaman and Nicobar Islands    RoC-Chennai  Company limited by shares
3     Andaman and Nicobar Islands    RoC-Chennai  Company limited by shares
4     Andaman and Nicobar Islands    RoC-Chennai  Company limited by shares
5     Andaman and Nicobar Islands    RoC-Chennai  Company limited by shares
...                           ...            ...                        ...
7363                    Telangana  RoC-Hyderabad  Company limited by shares
7364                    Telangana  RoC-Hyderabad  Company limited by shares
7365                    Telangana  RoC-Hyderabad  Company limited by shares
7366                    Telangana  RoC-Hyderabad  Company limited by shares
7367                    Telangana  RoC-Hyderabad  Company limited by shares

        CLASS S.No DATE_OF_REGISTRATION MONTH_NAME COMPANY_STATUS  \
1     Private  NaN                  NaN        NaN            NaN
2         OPC  NaN                  NaN        NaN            NaN
3     Private  NaN                  NaN        NaN            NaN
4     Private  NaN                  NaN        NaN            NaN
5     Private  NaN                  NaN        NaN            NaN
...       ...  ...                  ...        ...            ...
7363  Private  NaN                  NaN        NaN            NaN
7364  Private  NaN                  NaN        NaN            NaN
7365  Private  NaN                  NaN        NaN            NaN
7366  Private  NaN                  NaN        NaN            NaN
7367  Private  NaN                  NaN        NaN            NaN

     COMPANY_TYPE ACTIVITY_CODE ACTIVITY_DESCRIPTION REGISTERED_OFFICE_ADDRESS
1             NaN           NaN                  NaN                       NaN
2             NaN           NaN                  NaN                       NaN
3             NaN           NaN                  NaN                       NaN
4             NaN           NaN                  NaN                       NaN
5             NaN           NaN                  NaN                       NaN
...           ...           ...                  ...                       ...
7363          NaN           NaN                  NaN                       NaN
7364          NaN           NaN                  NaN                       NaN
7365          NaN           NaN                  NaN                       NaN
7366          NaN           NaN                  NaN                       NaN
7367          NaN           NaN                  NaN                       NaN

[7367 rows x 14 columns]>

In [ ]:
# merged_df = pd.DataFrame()

# # Iterate through each Excel file
# for file_path in file_paths:
#     if os.path.exists(file_path):
#         # Read the Excel file
#         df = pd.read_excel(file_path)

#         # Clean column names
#         df.columns = df.columns.str.strip().str.replace(' ', '_')

#         # Remove large sentences from the header
#         df = df.loc[:, ~df.iloc[0].astype(str).str.contains('sentence|another_sentence', case=False)]

#         # Ensure no repetition in column names
#         existing_columns = set(merged_df.columns)
#         new_columns = [col for col in df.columns if col not in existing_columns]

#         # Add new columns to merged DataFrame
#         for col in new_columns:
#             merged_df[col] = df[col]
#     else:
#         print(f"File not found: {file_path}")

# merged_df

,CIN,COMPANY_NAME,INC-29,DATE_OF_INCORPORATION,STATE,ROC,CATEGORY,SUB_CATEGORY,CLASS,AUTHORIZED_CAPITAL,...,Unnamed:_9,Unnamed:_10,Unnamed:_11,Unnamed:_12,Unnamed:_13,Unnamed:_14,Unnamed:_0,Unnamed:_1,Unnamed:_15,Unnamed:_16
0,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Details of Indian Companies Registered During...,NaN,NaN
1,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACTIVITY DESCRIPTION,REGISTERED OFFICE ADDRESS
3,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Construction,RR MEADOWS PRIVATE LIMITEDDAY&NIGHT HOSPITAL R...
4,U01403AP2016PTC098002,AMEYA INDIA PRIVATE LIMITED,*,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,108000,...,CATEGORY,AUTHORIZED_CAPITAL,PAIDUP_CAPITAL,ACTIVITY_CODE,ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS,NaN,S.No,Business Services,QUEZEAL TECHNOLOGIES PRIVATE LIMITEDDELHIH 189...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7362,U29214WB2016PTC209462,PEDROLLO PUMPS PRIVATE LIMITED,NaN,2016-01-29,West Bengal,RoC-Kolkata,Company limited by shares,Indian Non-Government Company,Private,500000,...,Company limited by shares,100000,100000,74999,Business Services,"1099-P, Sector 43, Gurgaon Haryana INDIA 1...",NaN,NaN,Business Services,MARKET BUG (OPC) PRIVATE LIMITEDVIVEKANAND ROA...
7363,U72300WB2016PTC209463,NOBOUNDS TECHNOLOGY PRIVATE LIMITED,NaN,2016-01-29,West Bengal,RoC-Kolkata,Company limited by shares,Indian Non-Government Company,Private,500000,...,Company limited by shares,1000000,1000000,74999,Business Services,"C-5/28, GROUND FLOOR, SECTOR- 15 ROHINI DELH...",NaN,NaN,Business Services,VALUETREE INFOTECH PRIVATE LIMITED (OPC)Vidyar...
7364,U74900WB2016PTC209465,LIFESONIC INNOVATIONS PRIVATE LIMITED,NaN,2016-01-29,West Bengal,RoC-Kolkata,Company limited by shares,Indian Non-Government Company,Private,100000,...,Company limited by shares,100000,100000,74999,Business Services,"F- 88, GALI NO-1, MOHAN BABA NAGAR, TAJPUR ROA...",NaN,NaN,Business Services,AMBARAM LEARNING SPACE (OPC) PRIVATELIMITED1st...
7365,U93000WB2016NPL209464,ARTSPOSITIVE PARTICIPATORY DEVELOPMENT ORGANIS...,NaN,2016-01-29,West Bengal,RoC-Kolkata,Company limited by guarantee,Indian Non-Government Company,Private,0,...,Company limited by shares,500000,200000,74999,Business Services,"CHAND NAGAR, PHULWARI SHARIF PATNA PATNA Bih...",NaN,NaN,Business Services,ORGANIC VILLAGE VENTURES PRIVATE LIMITED(OPC)B...
7366,U74900WB2016PLC209467,HARSMEN VANIJYA LIMITED,*,2016-01-29,West Bengal,RoC-Kolkata,Company limited by shares,Indian Non-Government Company,Public,500000,...,Company limited by shares,100000,100000,80301,"Community, personal & Social Services","SCO 88, LEVEL 2 DISTRICT SHOPPING COMPLEX,RANJ...",NaN,NaN,Business Services,"BHAVANSH INFRA LIMITED100 Ft Road,J.P.Nagar,2n..."

In [ ]:
# merged_df.value_counts

<bound method DataFrame.value_counts of                         CIN  \
0     U93000AP2016OPC098000
1     U45205AP2016PTC098009
2     U45400AP2016PTC098001
3     U72300AP2016PTC098004
4     U01403AP2016PTC098002
...                     ...
7362  U29214WB2016PTC209462
7363  U72300WB2016PTC209463
7364  U74900WB2016PTC209465
7365  U93000WB2016NPL209464
7366  U74900WB2016PLC209467

                                           COMPANY_NAME INC-29  \
0     KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...    NaN
1                MVS CONSTRUCTION INDIA PRIVATE LIMITED    NaN
2            VYBRANT INVESTO & PROJECTS PRIVATE LIMITED    NaN
3     LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...    NaN
4                           AMEYA INDIA PRIVATE LIMITED      *
...                                                 ...    ...
7362                     PEDROLLO PUMPS PRIVATE LIMITED    NaN
7363                NOBOUNDS TECHNOLOGY PRIVATE LIMITED    NaN
7364              LIFESONIC INNOVATIONS PRIVATE LIMITED    NaN
7365  ARTSPOSITIVE PARTICIPATORY DEVELOPMENT ORGANIS...    NaN
7366                            HARSMEN VANIJYA LIMITED      *

     DATE_OF_INCORPORATION           STATE            ROC  \
0               2016-01-01  Andhra Pradesh  RoC-Hyderabad
1               2016-01-01  Andhra Pradesh  RoC-Hyderabad
2               2016-01-01  Andhra Pradesh  RoC-Hyderabad
3               2016-01-01  Andhra Pradesh  RoC-Hyderabad
4               2016-01-01  Andhra Pradesh  RoC-Hyderabad
...                    ...             ...            ...
7362            2016-01-29     West Bengal    RoC-Kolkata
7363            2016-01-29     West Bengal    RoC-Kolkata
7364            2016-01-29     West Bengal    RoC-Kolkata
7365            2016-01-29     West Bengal    RoC-Kolkata
7366            2016-01-29     West Bengal    RoC-Kolkata

                          CATEGORY                   SUB_CATEGORY    CLASS  \
0        Company limited by shares  Indian Non-Government Company      OPC
1        Company limited by shares  Indian Non-Government Company  Private
2        Company limited by shares  Indian Non-Government Company  Private
3        Company limited by shares  Indian Non-Government Company  Private
4        Company limited by shares  Indian Non-Government Company  Private
...                            ...                            ...      ...
7362     Company limited by shares  Indian Non-Government Company  Private
7363     Company limited by shares  Indian Non-Government Company  Private
7364     Company limited by shares  Indian Non-Government Company  Private
7365  Company limited by guarantee  Indian Non-Government Company  Private
7366     Company limited by shares  Indian Non-Government Company   Public

      AUTHORIZED_CAPITAL  ...                 Unnamed:_9         Unnamed:_10  \
0                 100000  ...                        NaN                 NaN
1                 100000  ...                        NaN                 NaN
2                 100000  ...                        NaN                 NaN
3                1000000  ...                        NaN                 NaN
4                 108000  ...                   CATEGORY  AUTHORIZED_CAPITAL
...                  ...  ...                        ...                 ...
7362              500000  ...  Company limited by shares              100000
7363              500000  ...  Company limited by shares             1000000
7364              100000  ...  Company limited by shares              100000
7365                   0  ...  Company limited by shares              500000
7366              500000  ...  Company limited by shares              100000

         Unnamed:_11    Unnamed:_12                            Unnamed:_13  \
0                NaN            NaN                                    NaN
1                NaN            NaN                                    NaN
2                NaN            NaN                                    NaN
3                NaN            NaN                                    NaN
4     PAIDUP_CAPITAL  ACTIVITY_CODE                   ACTIVITY_DESCRIPTION
...              ...            ...                                    ...
7362          100000          74999                      Business Services
7363         1000000          74999                      Business Services
7364          100000          74999                      Business Services
7365          200000          74999                      Business Services
7366          100000          80301  Community, personal & Social Services

                                            Unnamed:_14 Unnamed:_0  \
0                                                   NaN        NaN
1                                                   NaN        NaN
2                                                   NaN        NaN
3                                                   NaN        NaN
4                             REGISTERED_OFFICE_ADDRESS        NaN
...                                                 ...        ...
7362  1099-P, Sector 43,     Gurgaon Haryana INDIA 1...        NaN
7363  C-5/28, GROUND FLOOR, SECTOR- 15 ROHINI   DELH...        NaN
7364  F- 88, GALI NO-1, MOHAN BABA NAGAR, TAJPUR ROA...        NaN
7365  CHAND NAGAR, PHULWARI SHARIF PATNA   PATNA Bih...        NaN
7366  SCO 88, LEVEL 2 DISTRICT SHOPPING COMPLEX,RANJ...        NaN

                                             Unnamed:_1           Unnamed:_15  \
0     Details of Indian Companies Registered  During...                   NaN
1                                                   NaN                   NaN
2                                                   NaN  ACTIVITY DESCRIPTION
3                                                   NaN          Construction
4                                                  S.No     Business Services
...                                                 ...                   ...
7362                                                NaN     Business Services
7363                                                NaN     Business Services
7364                                                NaN     Business Services
7365                                                NaN     Business Services
7366                                                NaN     Business Services

                                            Unnamed:_16
0                                                   NaN
1                                                   NaN
2                             REGISTERED OFFICE ADDRESS
3     RR MEADOWS PRIVATE LIMITEDDAY&NIGHT HOSPITAL R...
4     QUEZEAL TECHNOLOGIES PRIVATE LIMITEDDELHIH 189...
...                                                 ...
7362  MARKET BUG (OPC) PRIVATE LIMITEDVIVEKANAND ROA...
7363  VALUETREE INFOTECH PRIVATE LIMITED (OPC)Vidyar...
7364  AMBARAM LEARNING SPACE (OPC) PRIVATELIMITED1st...
7365  ORGANIC VILLAGE VENTURES PRIVATE LIMITED(OPC)B...
7366  BHAVANSH INFRA LIMITED100 Ft Road,J.P.Nagar,2n...

[7367 rows x 33 columns]>

In [ ]:
# common_columns = ['ACTIVITY DESCRIPTION', 'ACTIVITY CODE', 'AUTHORIZED CAPITAL', 'CATEGORY', 'CIN', 'CLASS', 'COMPANY NAME', 'COMPANY STATUS', 'COMPANY TYPE', 'DATE OF INCORPORATION', 'DATE OF REGISTRATION', 'INC-29', 'MONTH NAME', 'NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital)', 'PAID CAPITAL', 'PAIDUP CAPITAL', 'REGISTERED OFFICE ADDRESS', 'ROC', 'S.No', 'STATE', 'SUB CATEGORY']

In [ ]:
# common_columns = ['ACTIVITY DESCRIPTION', 'ACTIVITY CODE', 'AUTHORIZED CAPITAL', 'CATEGORY', 'CIN', 'CLASS',
#                   'COMPANY NAME', 'COMPANY STATUS', 'COMPANY TYPE', 'DATE OF INCORPORATION',
#                   'DATE OF REGISTRATION', 'INC-29', 'MONTH NAME',
#                   'NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital)',
#                   'PAID CAPITAL', 'PAIDUP CAPITAL', 'REGISTERED OFFICE ADDRESS', 'ROC', 'S.No', 'STATE',
#                   'SUB CATEGORY']

In [ ]:
# # Define the common columns in the desired order
# common_columns = ['ACTIVITY DESCRIPTION', 'ACTIVITY CODE', 'AUTHORIZED CAPITAL', 'CATEGORY', 'CIN', 'CLASS',
#                   'COMPANY NAME', 'COMPANY STATUS', 'COMPANY TYPE', 'DATE OF INCORPORATION',
#                   'DATE OF REGISTRATION', 'INC-29', 'MONTH NAME',
#                   'NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital)',
#                   'PAID CAPITAL', 'PAIDUP CAPITAL', 'REGISTERED OFFICE ADDRESS', 'ROC', 'S.No', 'STATE',
#                   'SUB CATEGORY']
# # Create an empty DataFrame
# merged_df = pd.DataFrame()

# # Iterate over each Excel file
# for file_path in file_paths:
#     if os.path.exists(file_path):
#         # Read the Excel file
#         df = pd.read_excel(file_path)

#         # Clean and standardize column names
#         df.columns = [str(col).strip().replace(' ', '_').upper() for col in df.columns]

#         # Extract columns based on common patterns
#         columns_to_add = [col for col in df.columns if any(keyword in str(col) for keyword in common_columns)]

#         # Append data to merged DataFrame
#         merged_df = pd.concat([merged_df, df[columns_to_add]], ignore_index=True)
#     else:
#         print(f"File not found: {file_path}")

# # Sort columns alphabetically and drop duplicates
# merged_df = merged_df.reindex(sorted(merged_df.columns), axis=1).drop_duplicates()

# # Save the merged DataFrame to a new Excel file
# merged_df.to_excel('merged_sheets.xlsx', index=False)

In [ ]:

# # Define the common columns in the desired order
# common_columns = ['ACTIVITY DESCRIPTION', 'ACTIVITY CODE', 'AUTHORIZED CAPITAL', 'CATEGORY', 'CIN', 'CLASS',
#                   'COMPANY NAME', 'COMPANY STATUS', 'COMPANY TYPE', 'DATE OF INCORPORATION',
#                   'DATE OF REGISTRATION', 'INC-29', 'MONTH NAME',
#                   'NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital)',
#                   'PAID CAPITAL', 'PAIDUP CAPITAL', 'REGISTERED OFFICE ADDRESS', 'ROC', 'S.No', 'STATE',
#                   'SUB CATEGORY']

# dfs = []

# # Iterate over each Excel file
# for file_path in file_paths:
#     if os.path.exists(file_path):
#         # Read the Excel file
#         df = pd.read_excel(file_path)

#         # Clean column names
#         df.columns = df.columns.str.strip().str.replace(' ', '_')

#         # Remove large sentences from the header
#         df = df.loc[:, ~df.iloc[0].astype(str).str.contains('sentence|another_sentence', case=False)]

#         # Ensure no repetition in column names
#         existing_columns = set(merged_df.columns)
#         new_columns = [col for col in df.columns if col not in existing_columns]

#         # Add new columns to merged DataFrame
#         for col in new_columns:
#             merged_df[col] = df[col]

#         # Append the DataFrame to the list
#         dfs.append(df)
#     else:
#         print(f"File not found: {file_path}")

# # Concatenate the DataFrames along the rows and reset index
# merged_df = pd.concat(dfs, ignore_index=True)
# merged_df

,CIN,COMPANY_NAME,INC-29,DATE_OF_INCORPORATION,STATE,ROC,CATEGORY,SUB_CATEGORY,CLASS,AUTHORIZED_CAPITAL,...,Unnamed:_9,Unnamed:_10,Unnamed:_11,Unnamed:_12,Unnamed:_13,Unnamed:_14,Unnamed:_0,Unnamed:_1,Unnamed:_15,Unnamed:_16
0,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U01403AP2016PTC098002,AMEYA INDIA PRIVATE LIMITED,*,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,108000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93747,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,96000,NaN,8228,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93748,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,90000,96000,NaN,8229,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93749,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,NaN,8230,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93750,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8231,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93751,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8232,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

In [ ]:
# List of your Excel file paths
file_paths = [
    '/content/drive/MyDrive/data for research/reg2016/Jan2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/feb2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_March2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_April2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_May2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_June2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_July2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_August2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_September2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_October2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_November2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_December2016.xlsx'
]

def find_data_start_row(file_path, max_inspect_rows=20, min_non_empty_cells=2):
    data = pd.read_excel(file_path, nrows=max_inspect_rows)
    for index, row in data.iterrows():
        non_empty_cells = row.dropna().shape[0]
        if non_empty_cells >= min_non_empty_cells:
            return index
    return 0

# Initialize an empty DataFrame to hold the combined data
combined_data = pd.DataFrame()

# Process each file
for file_path in file_paths:
    skip_rows = find_data_start_row(file_path)
    data = pd.read_excel(file_path, skiprows=skip_rows, header=None)
    combined_data = pd.concat([combined_data, data], ignore_index=True)

# Optional: Save the combined DataFrame to a new Excel file
combined_data.to_excel('/content/drive/MyDrive/combined_data.xlsx', index=False)

# merged_df is the combined DataFrame containing all the data
merged_df = combined_data

print("Data combined successfully. Total rows:", len(merged_df))

Data combined successfully. Total rows: 93746

In [ ]:
merged_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,CIN,COMPANY NAME,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,PAID CAPITAL,NUMBER OF MEMBERS (Applicable only in case of ...,ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS,NaN,NaN,NaN
1,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000,100000,0,"Community, personal & Social Services","Door No. 13-2-138/A, Ward No. 14, Tilak Nagar,...",NaN,NaN,NaN
2,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"1-125,JAYAVARAM VILLAGE & POST , PRAKASAM DIS...",NaN,NaN,NaN
3,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"Door No. 38-4-11A, 1st Floor, Montessori High ...",NaN,NaN,NaN
4,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000,100000,0,Business Services,"C/90, Anil Real Estate, Bodasingipeta, Bondapl...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,NaN,8228,U96000DL2016PTC309807,CYZOR PRIVATE LIMITED,2016-12-28 00:00:00,December,Delhi,ROC - DELHI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,96000,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93742,NaN,8229,U96000MP2016PTC042036,GET IRONMAN LAUNDRY PRIVATE LIMITED,2016-12-21 00:00:00,December,Madhya Pradesh,ROC - GWALIOR,Private,Active,Non-Government,Company Limited by Shares,100000,90000,96000,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93743,NaN,8230,U99000KL2016PTC047477,VSAFE HITECH SOLUTIONS PRIVATE LIMITED,2016-12-08 00:00:00,December,Kerala,ROC - ERNAKULAM,Private,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93744,NaN,8231,U99000MH2016PTC288064,SAJ FACILITIES MANAGEMENT PRIVATELIMITED,2016-12-01 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93745,NaN,8232,U99000MH2016PTC289123,INQUISITIVE COMMUNICATION PRIVATELIMITED,2016-12-30 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

In [ ]:
# import pandas as pd

# def find_data_start_row_and_columns_to_skip(file_path, max_inspect_rows=20, min_non_empty_cells=2):
#     data = pd.read_excel(file_path, nrows=max_inspect_rows)
#     start_row = 0
#     columns_to_skip = []

#     for index, row in data.iterrows():
#         non_empty_cells = row.dropna().shape[0]
#         if non_empty_cells >= min_non_empty_cells:
#             start_row = index
#             break

#     # Check if the second column is 'S.No' and should be skipped
#     header_row = pd.read_excel(file_path, skiprows=start_row, nrows=1)
#     if header_row.iloc[0, 1] == 'S.No':
#         columns_to_skip.append(1)

#     return start_row, columns_to_skip

# # Initialize an empty DataFrame to hold the combined data
# combined_data = pd.DataFrame()

# # Process each file
# for file_path in file_paths:
#     skip_rows, columns_to_skip = find_data_start_row_and_columns_to_skip(file_path)
#     data = pd.read_excel(file_path, skiprows=skip_rows, header=None, usecols=lambda column: column not in columns_to_skip)
#     combined_data = pd.concat([combined_data, data], ignore_index=True)

# # Optional: Save the combined DataFrame to a new Excel file
# # combined_data.to_excel('/content/drive/MyDrive/combined_data.xlsx', index=False)

# # merged_df is the combined DataFrame containing all the data
# merged_df = combined_data
# merged_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,CIN,COMPANY NAME,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,PAID CAPITAL,NUMBER OF MEMBERS (Applicable only in case of ...,ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS,NaN,NaN,NaN
1,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000,100000,0,"Community, personal & Social Services","Door No. 13-2-138/A, Ward No. 14, Tilak Nagar,...",NaN,NaN,NaN
2,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"1-125,JAYAVARAM VILLAGE & POST , PRAKASAM DIS...",NaN,NaN,NaN
3,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"Door No. 38-4-11A, 1st Floor, Montessori High ...",NaN,NaN,NaN
4,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000,100000,0,Business Services,"C/90, Anil Real Estate, Bodasingipeta, Bondapl...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,NaN,NaN,U96000DL2016PTC309807,CYZOR PRIVATE LIMITED,2016-12-28 00:00:00,December,Delhi,ROC - DELHI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,96000,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93742,NaN,NaN,U96000MP2016PTC042036,GET IRONMAN LAUNDRY PRIVATE LIMITED,2016-12-21 00:00:00,December,Madhya Pradesh,ROC - GWALIOR,Private,Active,Non-Government,Company Limited by Shares,100000,90000,96000,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93743,NaN,NaN,U99000KL2016PTC047477,VSAFE HITECH SOLUTIONS PRIVATE LIMITED,2016-12-08 00:00:00,December,Kerala,ROC - ERNAKULAM,Private,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93744,NaN,NaN,U99000MH2016PTC288064,SAJ FACILITIES MANAGEMENT PRIVATELIMITED,2016-12-01 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93745,NaN,NaN,U99000MH2016PTC289123,INQUISITIVE COMMUNICATION PRIVATELIMITED,2016-12-30 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,CIN,COMPANY NAME,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,PAID CAPITAL,NUMBER OF MEMBERS (Applicable only in case of ...,ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS,NaN,NaN,NaN
1,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000,100000,0,"Community, personal & Social Services","Door No. 13-2-138/A, Ward No. 14, Tilak Nagar,...",NaN,NaN,NaN
2,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"1-125,JAYAVARAM VILLAGE & POST , PRAKASAM DIS...",NaN,NaN,NaN
3,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"Door No. 38-4-11A, 1st Floor, Montessori High ...",NaN,NaN,NaN
4,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000,100000,0,Business Services,"C/90, Anil Real Estate, Bodasingipeta, Bondapl...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,NaN,8228,U96000DL2016PTC309807,CYZOR PRIVATE LIMITED,2016-12-28 00:00:00,December,Delhi,ROC - DELHI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,96000,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93742,NaN,8229,U96000MP2016PTC042036,GET IRONMAN LAUNDRY PRIVATE LIMITED,2016-12-21 00:00:00,December,Madhya Pradesh,ROC - GWALIOR,Private,Active,Non-Government,Company Limited by Shares,100000,90000,96000,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93743,NaN,8230,U99000KL2016PTC047477,VSAFE HITECH SOLUTIONS PRIVATE LIMITED,2016-12-08 00:00:00,December,Kerala,ROC - ERNAKULAM,Private,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93744,NaN,8231,U99000MH2016PTC288064,SAJ FACILITIES MANAGEMENT PRIVATELIMITED,2016-12-01 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93745,NaN,8232,U99000MH2016PTC289123,INQUISITIVE COMMUNICATION PRIVATELIMITED,2016-12-30 00:00:00,December,Maharashtra,ROC - MUMBAI,Private,Active,Non-Government,Company Limited by Shares,100000,100000,99000,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

In [ ]:
# import pandas as pd

# def find_data_start_row_and_columns_to_skip(file_path, max_inspect_rows=20, min_non_empty_cells=2):
#     """
#     Determines the start row for actual data and identifies the first two columns to skip if the second column contains 'S.No'.

#     Parameters:
#     - file_path (str): Path to the Excel file.
#     - max_inspect_rows (int): Maximum number of rows to inspect at the beginning of the file.
#     - min_non_empty_cells (int): Minimum number of non-empty cells to consider a row as containing actual data.

#     Returns:
#     - int: The index of the first row of actual data.
#     - list: A list of column indices to skip, specifically the first two columns if the second column contains 'S.No'.
#     """
#     # Read the first few rows to inspect the data
#     data = pd.read_excel(file_path, nrows=max_inspect_rows)
#     start_row = 0
#     columns_to_skip = []

#     # Determine the start row for actual data
#     for index, row in data.iterrows():
#         non_empty_cells = row.dropna().shape[0]
#         if non_empty_cells >= min_non_empty_cells:
#             start_row = index
#             break

#     # Read the header row to check if 'S.No' is in the second column
#     header = pd.read_excel(file_path, skiprows=start_row, nrows=1, header=None)
#     if header.shape[1] > 1 and header.iloc[0, 1] == 'S.No':  # Check if there are at least two columns and if the second column is 'S.No'
#         columns_to_skip = [0, 1]  # Skip the first two columns

#     return start_row, columns_to_skip

In [ ]:
# combined_data = pd.DataFrame()

# # Process each file
# for file_path in file_paths:
#     skip_rows, columns_to_skip = find_data_start_row_and_columns_to_skip(file_path)

#     # Use 'usecols' to skip unwanted columns
#     data = pd.read_excel(file_path, skiprows=skip_rows, header=0, usecols=lambda x: x not in columns_to_skip)

#     combined_data = pd.concat([combined_data, data], ignore_index=True)

# # Save the combined DataFrame to a new Excel file
# combined_data.to_excel('/content/drive/MyDrive/combined_data.xlsx', index=False)

# print("Data combined successfully. Total rows:", len(combined_data))

Data combined successfully. Total rows: 93734

In [ ]:
# combined_data

,CIN,COMPANY NAME,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,...,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 0,Unnamed: 1,Unnamed: 15,Unnamed: 16
0,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,NaN,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,1000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,U01403AP2016PTC098002,AMEYA INDIA PRIVATE LIMITED,*,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,108000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93729,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,96000,NaN,8228,"Community, personal & Social Services",PLOT NO 200 3rd FLOOR BLK-F PRASHANT VIHAR ROH...
93730,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,90000,96000,NaN,8229,"Community, personal & Social Services","17/7, SOUTH TUKOGANJJAIN MANDIR KE PICHHE Indo..."
93731,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,2500000,200000,99000,NaN,8230,"Community, personal & Social Services","DEVI GARDENS, TC 9/1615(1)(3)RAMAKRISHNA MISSI..."
93732,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8231,"Community, personal & Social Services",FLAT NO 1101 B WING GREEN HERITAGE CHSLPLOT NO...
93733,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,Active,Non-Government,Company Limited by Shares,100000,100000,99000,NaN,8232,"Community, personal & Social Services",C 605 PEARLS RAJHANS DREAMSSTELLA VASAI WEST V...

In [ ]:
# List of your Excel file paths
file_paths = [
    '/content/drive/MyDrive/data for research/reg2016/Jan2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/feb2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_March2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_April2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_May2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_June2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_July2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_August2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_September2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_October2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_November2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_December2016.xlsx'
]

def find_data_start_row(file_path, max_inspect_rows=20, min_non_empty_cells=2):
    data = pd.read_excel(file_path, nrows=max_inspect_rows)
    for index, row in data.iterrows():
        non_empty_cells = row.dropna().shape[0]
        if non_empty_cells >= min_non_empty_cells:
            return index
    return 0

# Initialize an empty DataFrame to hold the combined data
combined_data = pd.DataFrame()

# Process each file
for file_path in file_paths:
    skip_rows = find_data_start_row(file_path)
    data = pd.read_excel(file_path, skiprows=skip_rows, header=None)
    combined_data = pd.concat([combined_data, data], ignore_index=True)

# Optional: Save the combined DataFrame to a new Excel file
combined_data.to_excel('/content/drive/MyDrive/more to clean.xlsx', index=False)

# merged_df is the combined DataFrame containing all the data
merged_df = combined_data

print("Data combined successfully. Total rows:", len(merged_df))

Data combined successfully. Total rows: 93746

In [ ]:
import pandas as pd

# List of your Excel file paths
file_paths = [
    '/content/drive/MyDrive/data for research/reg2016/Jan2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/feb2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_March2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_April2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_May2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_June2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_July2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_August2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_September2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_October2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_November2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_December2016.xlsx'
]

def find_data_start_row(file_path, max_inspect_rows=20, min_non_empty_cells=2):
    data = pd.read_excel(file_path, nrows=max_inspect_rows)
    for index, row in data.iterrows():
        non_empty_cells = row.dropna().shape[0]
        if non_empty_cells >= min_non_empty_cells:
            return index
    return 0

# Initialize an empty DataFrame to hold the combined data
combined_data = pd.DataFrame()

# Process each file
for file_path in file_paths:
    skip_rows = find_data_start_row(file_path)

    # Skip first two columns
    data = pd.read_excel(file_path, skiprows=skip_rows, header=None, usecols=lambda x: x not in [0, 1])

    # Append each column
    for col in data.columns:
        col_name = data[col].iloc[0]  # Get the column name
        col_data = data[col].dropna().iloc[1:]  # Exclude header and empty rows
        if col_name not in combined_data.columns:
            combined_data[col_name] = col_data
        else:
            combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)

# Optional: Save the combined DataFrame to a new Excel file
#combined_data.to_excel('/content/drive/MyDrive/combined_data.xlsx', index=False)

# merged_df is the combined DataFrame containing all the data
merged_df = combined_data
merged_df

<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)
<ipython-input-5-193454f6001d>:44: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data[col_name] = combined_data[col_name].append(col_data, ignore_index=True)

,INC-29,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,AUTHORIZED_CAPITAL,PAID CAPITAL,NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital),ACTIVITY_DESCRIPTION,REGISTERED_OFFICE_ADDRESS,NaN
5,*,2016-01-01 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Business Services,"H.NO.1-244, Pulugurtha, Anaparthi Mandal East ...",Non-Government
6,*,2016-01-02 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,500000,100000,0,Mining & Quarrying,"H. No. 3-132, Champativariveedi Siddapuram Vil...",Company Limited by Shares
7,*,2016-01-02 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Construction,"3-224/12, Ganapathi nagar Atmakur, Mangalagiri...",Company Limited by Shares
8,*,2016-01-02 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Trading,"1/1255-8, YSR Colony, Near C.P Brown Library, ...",Company Limited by Shares
9,*,2016-01-02 00:00:00,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Business Services,"House No: 12-534/4 , Plot No : 20, Satya Garde...",Company Limited by Shares
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7346,NaN,2016-02-23 00:00:00,Maharashtra,RoC-Pune,Company limited by shares,Indian Non-Government Company,Private,1000000,700000,0,Business Services,"G NO. 76/B, KARANDWADI, SATARA Maharashtra I...","SAIGOKUL APP, S-5, 2ND FLR, 16TH A MN RD,14TH ..."
7347,NaN,2016-02-23 00:00:00,Maharashtra,RoC-Mumbai,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Business Services,"BLOCK NO.- 15, PLOT NO. - 36, PARISHRAM CHS NE...","Flat - 310, Sai Poorna ParadiseSomasandrapalya..."
7359,NaN,2016-02-23 00:00:00,Maharashtra,RoC-Pune,Company limited by shares,Indian Non-Government Company,Private,100000,100000,0,Business Services,"3rd Floor, Galore Tech, Survey No. 22 Hissa No...","NO 33/1ADUR, BIDARAHALLI HOBLI, VIRGONAGAR POS..."
7360,NaN,2016-02-23 00:00:00,Maharashtra,RoC-Mumbai,Company limited by shares,Indian Non-Government Company,Private,200000,100000,0,Business Services,UNIT NO. 237 HUBTOWN SOLARIS 2ND FLOOR N S PHA...,"800, P2, FIRST FLOOR, SECTOR-3HSR LAYOUT Banga..."
7367,NaN,2016-02-23 00:00:00,Maharashtra,RoC-Mumbai,Company limited by shares,Indian Non-Government Company,Private,200000,200000,0,Business Services,"Row House No 64, Chitalsar, Near Tikujini Wadi...","FLAT NO C G06, SEKHAR HYDEPARKNEAR DROUPADAMMA..."

In [8]:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [18]:
import pandas as pd

# List of your Excel file paths
file_paths = [
    '/content/drive/MyDrive/data for research/reg2016/Jan2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/feb2016_eir.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_March2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_April2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_May2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_June2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_July2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_August2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_September2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_October2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_November2016.xlsx',
    '/content/drive/MyDrive/data for research/reg2016/eir_December2016.xlsx'
]

# Define mapping of column names
column_mapping = {
    'CIN': ['CIN'],
    'COMPANY NAME': ['COMPANY NAME'],
    'DATE OF INCORPORATION': ['DATE OF INCORPORATION', 'DATE OF REGISTRATION'],
    'MONTH NAME': ['MONTH NAME'],
    'STATE': ['STATE'],
    'ROC': ['ROC'],
    'CATEGORY': ['CATEGORY'],
    'SUB CATEGORY': ['SUB CATEGORY'],
    'CLASS': ['CLASS'],
    'COMPANY STATUS': ['COMPANY STATUS'],
#    'AUTHORIZED CAPITAL': ['AUTHORIZED CAPITAL', 'AUTHORIZED_CAPITAL', 'AUTHORIZED_CAPITAL '],
    'PAID CAPITAL': ['PAID CAPITAL'],
    'COMPANY TYPE': ['COMPANY TYPE'],
    'ACTIVITY CODE': ['ACTIVITY CODE'],
 #   'NUMBER OF MEMBERS': ['NUMBER OF MEMBERS (Applicable only in case of Co. without share Capital)'],
 #   'ACTIVITY DESCRIPTION': ['ACTIVITY DESCRIPTION', 'ACTIVITY_DESCRIPTION'],
 #   'REGISTERED OFFICE ADDRESS': ['REGISTERED OFFICE ADDRESS', 'REGISTERED_OFFICE_ADDRESS']
}

# Initialize an empty DataFrame to hold the combined data
combined_data = pd.DataFrame()

# Process each file
for file_path in file_paths:
    # Read the data from the Excel file
    data = pd.read_excel(file_path)

    # Select only the columns we are interested in
    selected_columns = []
    for target_column, source_columns in column_mapping.items():
        found = False
        for column in source_columns:
            if column in data.columns:
                selected_columns.append(column)
                found = True
                break
        if not found:
            selected_columns.append(None)  # None indicates that the column wasn't found

    # Filter out None values and select only the relevant columns
    selected_columns = [col for col in selected_columns if col is not None]
    data = data[selected_columns]

    # Rename columns to match the desired names
    data.columns = [column_mapping[col][0] for col in selected_columns]

    # Append the data to the combined DataFrame
    combined_data = pd.concat([combined_data, data], ignore_index=True)

# Optional: Save the combined DataFrame to a new Excel file
combined_data.to_excel('/content/drive/MyDrive/combined_data.xlsx', index=False)

# merged_df is the combined DataFrame containing all the data
merged_df = combined_data

print("Data combined successfully. Total rows:", len(merged_df))

merged_df

Data combined successfully. Total rows: 93752

,CIN,COMPANY NAME,DATE OF INCORPORATION,STATE,ROC,CATEGORY,SUB CATEGORY,CLASS,PAID CAPITAL
0,U93000AP2016OPC098000,KAMAIAH ENGINEERING SERVICES PRIVATE LIMITED (...,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,OPC,100000.0
1,U45205AP2016PTC098009,MVS CONSTRUCTION INDIA PRIVATE LIMITED,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0
2,U45400AP2016PTC098001,VYBRANT INVESTO & PROJECTS PRIVATE LIMITED,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0
3,U72300AP2016PTC098004,LINCOLN TECHNOLOGY SOLUTIONS (INDIA) PRIVATE L...,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,100000.0
4,U01403AP2016PTC098002,AMEYA INDIA PRIVATE LIMITED,2016-01-01,Andhra Pradesh,RoC-Hyderabad,Company limited by shares,Indian Non-Government Company,Private,108000.0
...,...,...,...,...,...,...,...,...,...
93747,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
93748,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
93749,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
93750,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
93751,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN